### ISSUE TITLE
4x4 missed in portrait

### ISSUE THREAD

**Issue by tempral** [AChep/15puzzle#9]
![Screenshot_20200102-223214](https://user-images.githubusercontent.com/11719067/71694653-164f2100-2db0-11ea-9cc0-305782ae3743.jpg)

**Comment by AChep** [comment]
Fixed by 8b03e556907a02ba7d7dd6ca65481db21d12d084

**Comment by AChep** [comment]
The update is published on Play Store but still processing. Please, check this issue on a new build @tempral

**Comment by tempral** [comment]
thanks for the ultra fast solution, I checked now and it works!
but I found another imperfection, this time in landscape mode, screen width/height isn't enough to display content entirely
![Screenshot_20200103-232549](https://user-images.githubusercontent.com/11719067/71752776-a197e780-2e80-11ea-857b-bbb531b42a25.jpg)
![Screenshot_20200103-232557](https://user-images.githubusercontent.com/11719067/71752784-af4d6d00-2e80-11ea-9132-1b438e5e86f2.jpg)
